apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuc-platform
  labels:
    app: vuc-platform
    project: ultrachain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuc-platform
      project: ultrachain
  template:
    metadata:
      labels:
        app: vuc-platform
        project: ultrachain
    spec:
      containers:
        - name: vuc-platform
          image: ghcr.io/ultrachain/vuc-platform:latest
          ports:
            - containerPort: 8080
          env:
            - name: ULTRACHAIN_NETWORK
              value: "testnet" # ou testnet/devnet selon l’environnement
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vuc-platform-service
  labels:
    app: vuc-platform
    project: ultrachain
spec:
  selector:
    app: vuc-platform
    project: ultrachain
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP